////////EnsembleMembership/////////
@Membership
	// all MemberGroup annotations into a single Members annotation
	@Members({
		// the App group is aggregated from the ownerId knowledge primitive object
		@MemberGroup(identifier="App", aggregator="ownerId", size=5), 
		// the Scp group is pre-generated by the framework with middleware-supplied latencies
		@MemberGroup(identifier="Scp", isBestLatencyLinkageGroup=true, size=5)
	})
	public static Boolean membership(
			// AppComponent coordinator
			@In("coord.id") String cAppId,
			@In("coord.scpId") String cAppScpId,
			@In("coord.isDeployed") Boolean cAppIsDeployed,
			// AppComponent members
			@In("members.App.id") List<String> msAppIds,
			@In("members.App.scpId") List<String> msAppScpIds,
			@In("members.App.isDeployed") List<Boolean> msAppIsDeployed,
			// ScpComponent members
			@In("members.Scp.id") List<String> msScpIds,
			@In("members.Scp.appIds") List<List<String>> msScpAppIds
			) {
		// if all AppComponents have not been deployed yet
		// we suppose the input members arrays are not empty as being injected before the call
		if (!cAppIsDeployed &&
			!msAppIsDeployed.contains(false)){
			return true;
		}
		return null;
	}
	
////////AppComponent/////////
public class AppComponent extends Component {
	
	public final static long serialVersionUID = 1L;

	/**
	 * id of the SCP instance which the application component is processed by
	 */
	public String scpId;
	
	/**
	 * flag for deployment
	 */
	public Boolean isDeployed;
	
	//...
}
	
////////ScpComponent/////////
public class ScpComponent extends NetworkComponent {
	
	public final static long serialVersionUID = 1L;
	
	/**
	 * id of the application nodes which are linked to the scp
	 */
	public List<String> appIds;
	
	//...
}

////////NetworkComponent/////////
public class NetworkComponent extends Component {

	private static final long serialVersionUID = 1L;
	
	public ENetworkId networkId; // = which network does the component belong to
}

////////ENetworkId/////////
public enum ENetworkId {
	LMU_MUNICH,
	IMT_LUCCA,
	EN_GARDEN
}